WITH rawdata AS (
	SELECT 
		STU.ID,
		STU.FN,
		STU.LN,
		STU.MN,
		STU.GR,
		STU.PG,
		STU.TL,
		CAT.DT,
		CAT.SCL,
		CAT.AC,
		FTF.STI,
		CRS.CO
	FROM
		(SELECT STU.* FROM STU WHERE DEL = 0) STU
	LEFT JOIN
		(SELECT CAT.* FROM CAT WHERE DEL = 0) CAT
		ON STU.ID = CAT.ID
	LEFT JOIN
		(SELECT MST.* FROM MST WHERE DEL = 0) MST
		ON MST.SC = CAT.SCL
		AND MST.SE = CAT.SE
	LEFT JOIN
		(SELECT FTF.* FROM FTF WHERE DEL = 0) FTF
		ON MST.FSQ = FTF.SQ
	LEFT JOIN
		(SELECT CRS.* FROM CRS WHERE DEL = 0) CRS
		ON CRS.CN = MST.CN
	WHERE 
		NOT STU.TG > ' '
		--AND CAT.DT BETWEEN '12/2/2024' AND '12/6/2024'
		AND CAT.DT BETWEEN DATEADD(DAY, -((DATEPART(WEEKDAY, GETDATE()) + 5) % 7 + 7), CAST(GETDATE() AS DATE)) 
				       AND DATEADD(DAY, -((DATEPART(WEEKDAY, GETDATE()) + 1) % 7), CAST(GETDATE() AS DATE))
		AND CAT.SCL = 70 -- 72
		--AND CAT.SCL = 69

)

SELECT * FROM rawdata ORDER BY ID, CO;

/*
SELECT 
	DATEADD(DAY, -((DATEPART(WEEKDAY, GETDATE()) + 5) % 7 + 7), CAST(GETDATE() AS DATE)) AS MostRecentMonday,
	DATEADD(DAY, -((DATEPART(WEEKDAY, GETDATE()) + 1) % 7), CAST(GETDATE() AS DATE)) AS MostRecentFriday;
*/